server:
  #服务端口
  port: 81
#数据源配置
spring:
  redis:
    #redis的ip
    host: 127.0.0.1
    #redis的端口
    port: 6379
    #redis的密码
    password: rgPt1hBdqPtYJ0acpnfdmWbSHt09kH5T
    database: 0
    ssl: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/school?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # druid相关配置
    druid:
      # 初始化 最小 最大
      initial-size: 5
      min-idle: 5
      max-active: 110
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filter:
        stat:
          log-slow-sql: false
          slow-sql-millis: 1000

#crazy配置
crazy:
  prop:
    #上传文件访问域名，用于文件上传外网访问地址的拼接，文件上传后自动拼接此前缀
    upload-domain: http://localhost:1888
    #开启远程上传路径
    remote-mode: true
    # 设置文件上传路径，上传的静态资源都上传到了此路径下
    remote-path: D:\work\gitwork\产品\同舟网校\liveschool\src\main\resources
    # 系统的站点域名，用于系统中，支付宝，微信调用时的回调地址，后面要带上api结尾
    domain: https://wx.tongzhoushidai.com/api
    #前台站点域名(用于学员端支付，第三方登录时返回访问地址，拼接地址前缀时使用，必须配置)
    front-domain: https://wx.tongzhoushidai.com
    # 上传文件类型限制
    upload-file-type: jpg,png,jpeg,JPG,PNG,JPEG,docx,doc,xls,xlsx,ico
    # vue前台 icon上传路径
    front-icon-path: D:\tongzhou\favicon.ico
    # vue后台管理端 icon上传路径
    admin-icon-path: D:\tongzhou\liveschool-student-ui\favicon.ico
    # redis 缓存前缀
    redis-prefix: school_mater_1_1_5_lqx
    # 视频云服务域名(同舟视频云地址，如果使用了配置，如果不使用不配置也没事)
    videoyun-domain: http://videoyun.tongzhoushidai.com/api
  mybatis-plus:
    sql-log: true
